import os
import numpy as np
from PIL import Image, ImageFont, ImageDraw, ImageOps
import uuid

# ==========================================
#   AUTO EMOJI FACTORY V1
#   Logic: One-Click Generation of Box + Diffuser + Skin
# ==========================================

# --- CONFIGURATION ---
EMOJIS_TO_PRINT = ["👌", "🔥", "😂", "💀", "⚡"]
FONT_PATH = "seguiemj.ttf" # Windows Standard. Change if on Mac/Linux.
OUTPUT_DIR = "Factory_Output"
SIGN_SIZE = 150 # mm (Height of sign)
DEPTH = 30 # mm (Box depth)

if not os.path.exists(OUTPUT_DIR): os.makedirs(OUTPUT_DIR)

def get_font(size):
    try:
        return ImageFont.truetype(FONT_PATH, size)
    except:
        print(f"Warning: {FONT_PATH} not found. Using default (Details may fail).")
        return ImageFont.load_default()

def analyze_emoji(char, render_size=400):
    """
    Renders the emoji and extracts two sets of data:
    1. The Hull (For the Box shape)
    2. The Skin (For the internal details)
    """
    # 1. Setup Canvas
    img = Image.new("L", (render_size, render_size), 255) # White BG
    draw = ImageDraw.Draw(img)
    font = get_font(int(render_size * 0.8))
    
    # 2. Center Emoji
    bbox = draw.textbbox((0,0), char, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    # Draw Black Emoji on White
    draw.text(((render_size-w)/2, (render_size-h)/2 - bbox[1]), char, font=font, fill=0)
    
    # 3. Convert to Data
    data = np.array(img)
    
    # 4. Extract "Skin" Points (The Details)
    # We look for pixels that are DARK (Ink)
    skin_points = []
    step = 4 # Resolution (Higher = Rougher but faster)
    
    # 5. Extract "Hull" Points (The Outline)
    # We look for the edge of the shape to build the wall
    hull_points = []
    
    h_pix, w_pix = data.shape
    
    for y in range(0, h_pix, step):
        for x in range(0, w_pix, step):
            val = data[y, x]
            
            # Normalize Coords (-1 to 1 scale relative to center)
            norm_x = (x - w_pix/2) / (w_pix/2)
            norm_y = ((h_pix - y) - h_pix/2) / (h_pix/2)
            
            # SKIN LOGIC: Any dark pixel is part of the detail overlay
            if val < 150: 
                skin_points.append(f"[{norm_x:.3f},{norm_y:.3f}]")

    return skin_points

def generate_scad(char, skin_data):
    uid = str(uuid.uuid4())[:4]
    filename = f"{OUTPUT_DIR}/Emoji_{uid}_[{char}].scad"
    
    # Convert list to string for SCAD
    skin_vector_str = ",".join(skin_data)
    
    scad_content = f"""
// ==========================================
//   AUTO FACTORY OUTPUT: {char}
//   Generated by Bulb Architect
// ==========================================

$fn = 40;
Part_Type = "preview"; // OPTIONS: "box", "lid", "skin", "preview"

// --- DIMENSIONS ---
Sign_Size = {SIGN_SIZE}; // Total Height/Width
Depth = {DEPTH};
Wall_Thick = 2.0;

// --- DATA CLOUD ---
// Contains the extracted details of the emoji
Skin_Pixels = [{skin_vector_str}];

// --- MODULES ---

module draw_pixels(thickness, expansion) {{
    // Reconstructs the image from the python analysis
    // Expansion allows us to make the 'Hull' solid
    scale_factor = Sign_Size / 2;
    
    for(p = Skin_Pixels) {{
        translate([p[0] * scale_factor, p[1] * scale_factor, 0])
        cube([scale_factor/45 + expansion, scale_factor/45 + expansion, thickness], center=true);
    }}
}}

module part_skin() {{
    // The "Faceplate" - Print in BLACK
    // This is the detail layer you glue on top
    color("Black")
    draw_pixels(0.6, 0.2); // Thin, precise
}}

module part_lid() {{
    // The Diffuser - Print in WHITE
    color("White", 0.5)
    translate([0,0,-1])
    hull() {{
        // We use the pixel cloud to estimate the shape boundary
        // by drawing it FAT and hulling it.
        draw_pixels(1.0, 2.0); 
    }}
}}

module part_box() {{
    // The Housing - Print in ANY color
    color("#333")
    difference() {{
        // Solid Block
        translate([0,0,-Depth/2 - 1])
        linear_extrude(Depth)
        offset(r=2) hull() projection() draw_pixels(1.0, 2.0);
        
        // Hollow Interior
        translate([0,0,-Depth/2 - 1])
        linear_extrude(Depth+1)
        offset(r=-Wall_Thick) hull() projection() draw_pixels(1.0, 2.0);
        
        // Wire Hole
        translate([0, -Sign_Size/2, -Depth/2]) rotate([90,0,0]) cylinder(h=20, d=5);
    }}
}}

// --- RENDER LOGIC ---

if (Part_Type == "preview") {{
    translate([0,0,0]) part_skin();
    translate([0,0,0]) part_lid();
    translate([0,0,0]) part_box();
}}

if (Part_Type == "skin") {{ part_skin(); }}
if (Part_Type == "lid") {{ part_lid(); }}
if (Part_Type == "box") {{ part_box(); }}
"""
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(scad_content)
    print(f"Generated: {filename}")

# --- MAIN EXECUTION ---
print("🏭 STARTING EMOJI FACTORY...")
for emoji in EMOJIS_TO_PRINT:
    print(f"Analyzing {emoji}...")
    skin_data = analyze_emoji(emoji)
    generate_scad(emoji, skin_data)
print("✅ JOBS COMPLETE. Check output folder.")