import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import os
import math

# ==========================================
#   BULB ARCHITECT: REVERSE ENGINEERING ENGINE
#   Logic: Parametric Battery Enclosures
# ==========================================

class BulbArchitectApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Bulb Architect - Modular Power Systems")
        self.root.geometry("600x700")
        self.root.configure(bg="#222")

        self.setup_ui()

    def setup_ui(self):
        # Header
        header = tk.Label(self.root, text="BULB ARCHITECT", font=("Segoe UI", 16, "bold"), bg="#222", fg="#fff")
        header.pack(pady=15)

        # --- CONTROLS ---
        frame = tk.Frame(self.root, bg="#333", padx=20, pady=20)
        frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=10)

        # 1. Battery Selection
        tk.Label(frame, text="1. Power Source (Internal)", bg="#333", fg="#03A9F4", font=("Arial", 10, "bold")).pack(anchor="w")
        
        self.batt_var = tk.StringVar(value="CR2032 (Coin)")
        batt_options = ["CR2032 (Coin)", "AAA (x1)", "AAA (x2)", "AA (x1)", "18650 (Lithium)"]
        ttk.Combobox(frame, textvariable=self.batt_var, values=batt_options, state="readonly").pack(fill=tk.X, pady=5)

        # 2. Bulb Shape
        tk.Label(frame, text="2. Diffuser Shape", bg="#333", fg="#03A9F4", font=("Arial", 10, "bold")).pack(anchor="w", pady=(15,0))
        
        self.shape_var = tk.StringVar(value="Standard (A19)")
        shape_options = ["Standard (A19)", "Globe (G25)", "Edison (ST64)", "Tube (T45)"]
        ttk.Combobox(frame, textvariable=self.shape_var, values=shape_options, state="readonly").pack(fill=tk.X, pady=5)

        # 3. Filament Mount Style
        tk.Label(frame, text="3. Filament Geometry", bg="#333", fg="#03A9F4", font=("Arial", 10, "bold")).pack(anchor="w", pady=(15,0))
        
        self.fil_var = tk.StringVar(value="Double Helix")
        fil_options = ["Straight Pillar", "Double Helix", "Zig-Zag", "Heart Shape"]
        ttk.Combobox(frame, textvariable=self.fil_var, values=fil_options, state="readonly").pack(fill=tk.X, pady=5)

        # 4. Pattern Logic (Your Diffusion)
        tk.Label(frame, text="4. Scott Diffusion Pattern", bg="#333", fg="#03A9F4", font=("Arial", 10, "bold")).pack(anchor="w", pady=(15,0))
        
        self.pattern_var = tk.StringVar(value="None (Clear)")
        pattern_options = ["None (Clear)", "Houndstooth", "Burberry", "Hex-Grid", "Voronoi"]
        ttk.Combobox(frame, textvariable=self.pattern_var, values=pattern_options, state="readonly").pack(fill=tk.X, pady=5)

        # GENERATE BUTTON
        btn = tk.Button(self.root, text="GENERATE BLUEPRINTS (.SCAD)", command=self.generate, 
                       bg="#00E676", fg="black", font=("Arial", 12, "bold"), height=2)
        btn.pack(fill=tk.X, padx=20, pady=20)

        # Info
        tk.Label(self.root, text="Generates fully threaded, interlocking assembly.", bg="#222", fg="#888").pack()

    def generate(self):
        # Save Dialog
        filename = filedialog.asksaveasfilename(defaultextension=".scad", filetypes=[("OpenSCAD", "*.scad")])
        if not filename: return

        # Get Parameters
        batt_type = self.batt_var.get()
        bulb_shape = self.shape_var.get()
        fil_style = self.fil_var.get()
        pattern = self.pattern_var.get()

        # Generate Code
        scad_code = self.get_scad_logic(batt_type, bulb_shape, fil_style, pattern)
        
        with open(filename, "w") as f:
            f.write(scad_code)
        
        messagebox.showinfo("Success", f"Engineering Files Generated:\n{os.path.basename(filename)}")

    def get_scad_logic(self, batt, shape, fil, pat):
        # PARAMETRIC LOGIC DATABASE
        # Battery Dimensions [Dia, Height]
        batt_dims = {
            "CR2032 (Coin)": [22, 5],
            "AAA (x1)": [11, 45],
            "AAA (x2)": [22, 45], # Side by side
            "AA (x1)": [15, 51],
            "18650 (Lithium)": [19, 66]
        }
        bd = batt_dims[batt]
        
        # Determine Base Height based on Battery
        base_h = max(30, bd[1] + 10) 
        base_w = max(28, bd[0] + 6) # Standard E27 is 27mm, might need to scale up for 18650/AAx2

        return f"""
// ==========================================
//   BULB ARCHITECT MANIFEST
//   Generated by Scott Protocol
// ==========================================

$fn = 80;

// --- PARAMETERS ---
Battery_Type = "{batt}";
Bulb_Shape = "{shape}";
Filament_Type = "{fil}";
Pattern = "{pat}";

// Dimensions
Batt_Dia = {bd[0]};
Batt_Height = {bd[1]};
Base_Height = {base_h}; 
Base_Dia = {base_w}; 

// --- MODULES ---

module thread_e27(h) {{
    // Standard E27 Screw Thread Logic
    linear_extrude(height=h, twist=-360*(h/5), slices=h*4)
    translate([13, 0, 0])
    circle(r=1.5);
}}

module locking_thread_male() {{
    // The "Scott Lock" for the bulb-to-base connection
    linear_extrude(height=5, twist=-180, slices=50)
    translate([(Base_Dia/2)-1, 0, 0])
    square([1.5, 1.5], center=true);
}}

module locking_thread_female() {{
    // The inverse for the bulb
    linear_extrude(height=6, twist=-180, slices=50)
    translate([(Base_Dia/2)-1, 0, 0])
    scale([1.1, 1.1]) square([1.5, 1.5], center=true);
}}

// 1. THE POWER BASE (Holds Battery)
module power_base() {{
    difference() {{
        union() {{
            // Main Body
            cylinder(h=Base_Height, d=Base_Dia);
            // External E27 Threads (Aesthetic/Mounting)
            translate([0,0,2]) thread_e27(Base_Height-10);
            // Top Locking Ring
            translate([0,0,Base_Height]) cylinder(h=5, d=Base_Dia-2);
            translate([0,0,Base_Height]) locking_thread_male();
        }}
        
        // BATTERY CAVITY (Parametric)
        translate([0,0,2])
        if (Battery_Type == "AAA (x2)") {{
            // Dual Slot
            translate([6,0,0]) cylinder(h=Batt_Height+2, d=11.5);
            translate([-6,0,0]) cylinder(h=Batt_Height+2, d=11.5);
        }} else {{
            // Single Slot
            cylinder(h=Batt_Height+2, d=Batt_Dia+1);
        }}
        
        // Wiring Channel to Filament
        cylinder(h=Base_Height+10, d=3);
    }}
}}

// 2. THE DIFFUSER (The Bulb)
module bulb_shell() {{
    translate([0,0,Base_Height]) 
    difference() {{
        union() {{
            // Bulb Shape Logic
            if (Bulb_Shape == "Globe (G25)") {{
                translate([0,0,40]) sphere(d=80);
                cylinder(h=40, d1=Base_Dia, d2=80); // Neck
            }} else if (Bulb_Shape == "Edison (ST64)") {{
                translate([0,0,60]) sphere(d=64);
                cylinder(h=60, d1=Base_Dia, d2=64); // Long Neck
            }} else {{
                // Standard A19
                translate([0,0,30]) sphere(d=60);
                cylinder(h=30, d1=Base_Dia, d2=60);
            }}
        }}
        
        // Hollow Interior (Wall Thickness)
        // This is where Scott Diffusion Pattern would subtract
        union() {{
            if (Bulb_Shape == "Globe (G25)") {{
                translate([0,0,40]) sphere(d=78);
                cylinder(h=40, d1=Base_Dia-2, d2=78);
            }} else if (Bulb_Shape == "Edison (ST64)") {{
                translate([0,0,60]) sphere(d=62);
                cylinder(h=60, d1=Base_Dia-2, d2=62);
            }} else {{
                translate([0,0,30]) sphere(d=58);
                cylinder(h=30, d1=Base_Dia-2, d2=58);
            }}
        }}
        
        // The Pattern Subtraction (Placeholder for logic)
        // if (Pattern == "Houndstooth") ... 
        
        // Thread Interface (Female)
        translate([0,0,-1]) cylinder(h=7, d=Base_Dia);
        translate([0,0,0]) locking_thread_female();
    }}
}}

// 3. THE FILAMENT CHASSIS (Holds LED)
module filament_holder() {{
    translate([0,0,Base_Height + 5])
    union() {{
        // Base Plug (Fits into Battery Cavity top)
        translate([0,0,-5]) cylinder(h=4, d=Batt_Dia);
        
        // The Structure
        if (Filament_Type == "Double Helix") {{
            linear_extrude(height=40, twist=360)
            translate([5,0,0]) circle(r=1);
            
            linear_extrude(height=40, twist=-360)
            translate([5,0,0]) circle(r=1);
        }} else if (Filament_Type == "Zig-Zag") {{
            // Simple zig zag structure
            for(i=[0:5:35]) {{
                translate([-5,0,i]) rotate([0,45,0]) cube([10, 1, 1]);
                translate([0,0,i+2.5]) rotate([0,-45,0]) cube([10, 1, 1]);
            }}
        }} else {{
            // Straight Pillar
            cylinder(h=40, d=2);
            translate([0,0,40]) sphere(d=4);
        }}
    }}
}}

// --- RENDER LAYOUT ---
// Separated for printing
translate([-40, 0, 0]) power_base();
translate([40, 0, 0]) bulb_shell();
translate([0, 40, 0]) filament_holder();

"""

if __name__ == "__main__":
    root = tk.Tk()
    app = BulbArchitectApp(root)
    root.mainloop()