/**
 * ANIMATION SEQUENCE GENERATOR
 * Creates multi-frame LED animations with controller code generation
 * 
 * Features:
 * - Frame-based animation system (1-20 frames)
 * - Per-frame LED pattern control
 * - Arduino/ESP32 controller code generation
 * - Adjustable frame delay and animation speed
 * - Loop animation support
 * - PWM dimming control
 * 
 * Perfect for animated signs, moving figures, and interactive displays
 */

import * as THREE from "three";

interface Point2D {
  x: number;
  y: number;
}

/**
 * Animation Sequence Settings
 */
export interface AnimationSequenceSettings {
  // Sequence Configuration
  sequenceName: string;
  frameCount: number; // 1-20 frames
  frameDelay: number; // ms between frames
  animationSpeed: number; // FPS (frames per second)
  loopAnimation: boolean;
  
  // Frame Data
  frames: FrameConfig[];
  
  // LED Configuration
  ledType: "ws2812b" | "simple_led" | "neopixel";
  ledCount: number; // Total LEDs in system
  ledPin: number; // Data pin for addressable LEDs
  
  // Controller
  controllerType: "arduino_nano" | "esp32" | "xiao_samd21";
  includeDimmer: boolean;
  dimmerPin: number;
  brightnessLevels: number; // 1-255
  
  // Physical Dimensions
  signWidth: number; // mm
  signHeight: number; // mm
  
  // Export Options
  exportFormat: "stl" | "3mf";
  includeControllerCode: boolean;
  includeWiringDiagram: boolean;
}

/**
 * Individual Frame Configuration
 */
export interface FrameConfig {
  frameNumber: number;
  frameName: string;
  patternType: "stick_figure" | "text" | "shape" | "custom";
  ledPattern: number[]; // Array of LED indices that are ON for this frame
  brightness: number; // 0-255
  color: { r: number; g: number; b: number };
  duration: number; // ms to display this frame (overrides global frameDelay)
}

/**
 * Default settings for animation sequence
 */
export const defaultAnimationSequenceSettings: AnimationSequenceSettings = {
  sequenceName: "Walking Stick Figure",
  frameCount: 4,
  frameDelay: 500,
  animationSpeed: 2.0,
  loopAnimation: true,
  
  frames: [
    {
      frameNumber: 1,
      frameName: "Stick Figure - Step 1",
      patternType: "stick_figure",
      ledPattern: [0, 1, 2, 3, 4, 5, 10, 11],
      brightness: 255,
      color: { r: 255, g: 255, b: 255 },
      duration: 500,
    },
    {
      frameNumber: 2,
      frameName: "Stick Figure - Step 2",
      patternType: "stick_figure",
      ledPattern: [0, 1, 2, 3, 6, 7, 12, 13],
      brightness: 255,
      color: { r: 255, g: 255, b: 255 },
      duration: 500,
    },
    {
      frameNumber: 3,
      frameName: "Stick Figure - Step 3",
      patternType: "stick_figure",
      ledPattern: [0, 1, 2, 3, 8, 9, 14, 15],
      brightness: 255,
      color: { r: 255, g: 255, b: 255 },
      duration: 500,
    },
    {
      frameNumber: 4,
      frameName: "Stick Figure - Step 4",
      patternType: "stick_figure",
      ledPattern: [0, 1, 2, 3, 4, 5, 10, 11],
      brightness: 255,
      color: { r: 255, g: 255, b: 255 },
      duration: 500,
    },
  ],
  
  ledType: "ws2812b",
  ledCount: 60,
  ledPin: 3,
  
  controllerType: "arduino_nano",
  includeDimmer: true,
  dimmerPin: 5,
  brightnessLevels: 255,
  
  signWidth: 60,
  signHeight: 80,
  
  exportFormat: "stl",
  includeControllerCode: true,
  includeWiringDiagram: true,
};

/**
 * Generate Arduino controller code for animation sequence
 */
export function generateAnimationControllerCode(settings: AnimationSequenceSettings): string {
  const controllerName = settings.controllerType.toUpperCase().replace('_', ' ');
  
  return `/*
 * ${settings.sequenceName} - Animation Controller
 * Generated by Sign-Sculptor Animation Sequence System
 * 
 * Controller: ${controllerName}
 * LED Type: ${settings.ledType.toUpperCase()}
 * Frame Count: ${settings.frameCount}
 * Animation Speed: ${settings.animationSpeed} FPS
 * Loop: ${settings.loopAnimation ? 'Yes' : 'No'}
 */

#include <FastLED.h>

// LED Configuration
#define LED_PIN ${settings.ledPin}
#define NUM_LEDS ${settings.ledCount}
#define LED_TYPE WS2812B
#define COLOR_ORDER GRB
#define BRIGHTNESS ${settings.brightnessLevels}

// Animation Configuration
#define FRAME_COUNT ${settings.frameCount}
#define FRAME_DELAY ${settings.frameDelay}
#define LOOP_ANIMATION ${settings.loopAnimation ? 'true' : 'false'}

${settings.includeDimmer ? `// Dimmer Configuration
#define DIMMER_PIN ${settings.dimmerPin}
int currentBrightness = BRIGHTNESS;
` : ''}

// LED Array
CRGB leds[NUM_LEDS];

// Current frame index
int currentFrame = 0;
unsigned long lastFrameTime = 0;

// Frame LED patterns (1 = ON, 0 = OFF)
const bool framePatterns[FRAME_COUNT][NUM_LEDS] = {
${settings.frames.map((frame, frameIndex) => {
  const pattern = Array(settings.ledCount).fill(false);
  frame.ledPattern.forEach(ledIndex => {
    if (ledIndex < settings.ledCount) pattern[ledIndex] = true;
  });
  return `  { ${pattern.map(p => p ? '1' : '0').join(', ')} }${frameIndex < settings.frameCount - 1 ? ',' : ''}`;
}).join('\n')}
};

// Frame colors (RGB)
const CRGB frameColors[FRAME_COUNT] = {
${settings.frames.map((frame, frameIndex) => 
  `  CRGB(${frame.color.r}, ${frame.color.g}, ${frame.color.b})${frameIndex < settings.frameCount - 1 ? ',' : ''}`
).join('\n')}
};

// Frame durations (ms)
const int frameDurations[FRAME_COUNT] = {
${settings.frames.map((frame, frameIndex) => 
  `  ${frame.duration}${frameIndex < settings.frameCount - 1 ? ',' : ''}`
).join('\n')}
};

void setup() {
  Serial.begin(115200);
  Serial.println("${settings.sequenceName} - Animation Starting");
  
  // Initialize FastLED
  FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS);
  FastLED.setBrightness(BRIGHTNESS);
  FastLED.clear();
  FastLED.show();
  
${settings.includeDimmer ? `  // Initialize dimmer pin
  pinMode(DIMMER_PIN, INPUT);
` : ''}
  
  Serial.println("Setup complete!");
}

void loop() {
  unsigned long currentTime = millis();
  
${settings.includeDimmer ? `  // Read dimmer value
  int dimmerValue = analogRead(DIMMER_PIN);
  currentBrightness = map(dimmerValue, 0, 1023, 10, 255);
  FastLED.setBrightness(currentBrightness);
` : ''}
  
  // Check if it's time to advance to next frame
  if (currentTime - lastFrameTime >= frameDurations[currentFrame]) {
    lastFrameTime = currentTime;
    
    // Display current frame
    displayFrame(currentFrame);
    
    // Advance to next frame
    currentFrame++;
    
    // Handle loop or stop
    if (currentFrame >= FRAME_COUNT) {
      if (LOOP_ANIMATION) {
        currentFrame = 0;
        Serial.println("Animation loop restart");
      } else {
        currentFrame = FRAME_COUNT - 1; // Stay on last frame
        Serial.println("Animation complete (no loop)");
      }
    }
    
    Serial.print("Frame: ");
    Serial.print(currentFrame + 1);
    Serial.print("/");
    Serial.println(FRAME_COUNT);
  }
}

void displayFrame(int frameIndex) {
  // Clear all LEDs
  FastLED.clear();
  
  // Set LEDs according to frame pattern
  for (int i = 0; i < NUM_LEDS; i++) {
    if (framePatterns[frameIndex][i]) {
      leds[i] = frameColors[frameIndex];
    }
  }
  
  // Update LED strip
  FastLED.show();
}

// Helper function to set all LEDs to a color (for testing)
void setAllLEDs(CRGB color) {
  for (int i = 0; i < NUM_LEDS; i++) {
    leds[i] = color;
  }
  FastLED.show();
}

// Helper function to test individual LEDs
void testLEDs() {
  Serial.println("Testing LEDs...");
  for (int i = 0; i < NUM_LEDS; i++) {
    FastLED.clear();
    leds[i] = CRGB::White;
    FastLED.show();
    delay(100);
    Serial.print("LED ");
    Serial.print(i);
    Serial.println(" ON");
  }
  FastLED.clear();
  FastLED.show();
  Serial.println("Test complete");
}
`;
}

/**
 * Generate routing/wiring instructions
 */
export function generateAnimationWiringDiagram(settings: AnimationSequenceSettings): string {
  const controllerName = settings.controllerType.replace('_', ' ').toUpperCase();
  
  return `# Animation Sequence Wiring Diagram

## Controller: ${controllerName}

### LED Strip Connection:
\`\`\`
${settings.ledType.toUpperCase()} LED Strip
┌──────────────────────────────────────┐
│ DI (Data In)  → Pin ${settings.ledPin} (with 220Ω resistor)
│ 5V            → 5V Power Supply
│ GND           → Ground
└──────────────────────────────────────┘
\`\`\`

### Power Supply:
\`\`\`
5V Power Supply (Recommended: 2A minimum)
┌──────────────────────────────────────┐
│ +5V  → LED Strip 5V
│ GND  → LED Strip GND + Controller GND
└──────────────────────────────────────┘
\`\`\`

${settings.includeDimmer ? `### Dimmer Potentiometer:
\`\`\`
50kΩ Potentiometer
┌──────────────────────────────────────┐
│ Pin 1 (Left)   → 5V
│ Pin 2 (Middle) → Pin ${settings.dimmerPin} (Analog Input)
│ Pin 3 (Right)  → GND
└──────────────────────────────────────┘
\`\`\`
` : ''}

### Complete Wiring Schematic:
\`\`\`
        ${controllerName}
        ┌─────────────┐
        │             │
        │  Pin ${settings.ledPin} ────┼──→ 220Ω ──→ LED Data In
        │             │
${settings.includeDimmer ? `        │  Pin ${settings.dimmerPin} ────┼──→ Potentiometer (middle pin)
        │             │
` : ''}        │  5V  ───────┼──→ Power Supply +5V
        │  GND ───────┼──→ Power Supply GND
        │             │
        └─────────────┘
\`\`\`

### LED Count: ${settings.ledCount} LEDs
**Power Requirements:**
- Per LED: ~60mA at full white brightness
- Total (all LEDs): ~${(settings.ledCount * 0.06).toFixed(1)}A at full brightness
- Recommended PSU: ${Math.ceil(settings.ledCount * 0.06 * 1.5)}A (with 50% safety margin)

### Important Notes:
1. **Always use 220Ω resistor** on LED data line
2. **Connect grounds together** (controller + LED strip + power supply)
3. **Power LED strip directly** from power supply, not through controller
4. **Keep data wire short** (<1 meter) or use twisted pair
5. **Add 1000µF capacitor** across power supply for stability

---
Generated by Sign-Sculptor Animation Sequence System
`;
}

/**
 * Generate assembly instructions
 */
export function generateAnimationAssemblyInstructions(settings: AnimationSequenceSettings): string {
  return `# ${settings.sequenceName} - Assembly Instructions

## Overview
This animation sequence consists of ${settings.frameCount} frames running at ${settings.animationSpeed} FPS.

## Parts Required

### 3D Printed Parts:
${settings.frames.map((frame) => `- Frame ${frame.frameNumber}: ${frame.frameName}.stl`).join('\n')}
- Controller housing (if included)
- LED mounting channels

### Electronic Components:
- **${settings.ledType.toUpperCase()} LED Strip** (${settings.ledCount} LEDs)
- **${settings.controllerType.replace('_', ' ').toUpperCase()} Microcontroller**
- **220Ω Resistor** (1×) - Data line protection
- **5V Power Supply** (${Math.ceil(settings.ledCount * 0.06 * 1.5)}A minimum)
${settings.includeDimmer ? `- **50kΩ Potentiometer** (1×) - Brightness control` : ''}
- **22 AWG Wire** (red, black, yellow)
- **JST Connectors** (optional, for easy disconnection)

### Tools:
- Soldering iron
- Wire strippers
- Hot glue gun
- Multimeter (for testing)

## Assembly Steps

### Step 1: Print All Frames (${settings.frameCount * 2}-${settings.frameCount * 3} hours)
1. Print each frame STL file
2. Material: White PLA or PETG
3. Layer height: 0.2mm
4. Infill: 15%
5. Supports: None (optimized design)

### Step 2: Install LED Strips (45 minutes)
1. Measure LED strip length for each frame
2. Cut strips at designated cut points (every 3 LEDs)
3. Solder data line connections between frames:
   - Frame 1 DO → Frame 2 DI
   - Frame 2 DO → Frame 3 DI
   - Continue for all ${settings.frameCount} frames
4. Test continuity with multimeter
5. Secure strips with hot glue or mounting clips

### Step 3: Wire Controller (30 minutes)
1. Solder wires to controller:
   - Pin ${settings.ledPin} → Yellow wire (LED data)
   - 5V → Red wire (power)
   - GND → Black wire (ground)
${settings.includeDimmer ? `   - Pin ${settings.dimmerPin} → Potentiometer middle pin` : ''}
2. Add 220Ω resistor inline with yellow wire
3. Connect LED strip:
   - Yellow → LED DI (first LED)
   - Red → LED 5V
   - Black → LED GND
4. Connect power supply:
   - Red → PSU +5V
   - Black → PSU GND

### Step 4: Upload Arduino Code (15 minutes)
1. Install Arduino IDE (if not installed)
2. Add board support for ${settings.controllerType.replace('_', ' ')}
3. Install FastLED library (Tools → Manage Libraries)
4. Open generated .ino file
5. Select correct board and port
6. Click Upload
7. Wait for "Done uploading" message

### Step 5: Test Animation (10 minutes)
1. Power on system
2. Open Serial Monitor (115200 baud)
3. Verify frames cycle correctly
4. Check frame timing (${settings.frameDelay}ms per frame)
${settings.includeDimmer ? `5. Test dimmer potentiometer (rotate to adjust brightness)` : ''}
6. Confirm ${settings.loopAnimation ? 'animation loops continuously' : 'animation stops on last frame'}

### Step 6: Final Assembly (20 minutes)
1. Mount controller in housing (if included)
2. Route wires through channels
3. Secure all connections with hot glue
4. Add strain relief to power cable
5. Test one final time before sealing

## Animation Details

### Frame Sequence:
${settings.frames.map((frame) => `**Frame ${frame.frameNumber}**: ${frame.frameName}
- Duration: ${frame.duration}ms
- LEDs Active: ${frame.ledPattern.length}
- Color: RGB(${frame.color.r}, ${frame.color.g}, ${frame.color.b})
- Brightness: ${frame.brightness}/255`).join('\n\n')}

### Timing:
- **Frame Delay**: ${settings.frameDelay}ms
- **Animation Speed**: ${settings.animationSpeed} FPS
- **Total Cycle Time**: ${settings.frames.reduce((sum, f) => sum + f.duration, 0)}ms
- **Loop**: ${settings.loopAnimation ? 'Enabled' : 'Disabled'}

## Troubleshooting

### LEDs Don't Light:
- Check 220Ω resistor on data line
- Verify power supply voltage (should be 5V)
- Test LED strip separately
- Check solder joints

### Animation Doesn't Play:
- Verify code uploaded successfully
- Check Serial Monitor for errors
- Ensure LED_PIN matches wiring
- Test with testLEDs() function

### Wrong Frame Order:
- Check LED data line continuity
- Verify frame order in code
- Ensure no reversed connections

### Flickering:
- Add 1000µF capacitor across power supply
- Check for loose connections
- Verify power supply current rating
- Reduce brightness if underpowered

## Customization

### Adjust Animation Speed:
Change \`FRAME_DELAY\` in code (line 19):
\`\`\`cpp
#define FRAME_DELAY 500  // Change to desired ms
\`\`\`

### Change Colors:
Modify \`frameColors\` array (lines 40-44):
\`\`\`cpp
const CRGB frameColors[FRAME_COUNT] = {
  CRGB(255, 0, 0),    // Red
  CRGB(0, 255, 0),    // Green
  CRGB(0, 0, 255),    // Blue
  CRGB(255, 255, 0)   // Yellow
};
\`\`\`

### Add More Frames:
1. Increase \`FRAME_COUNT\`
2. Add new patterns to \`framePatterns\` array
3. Add new colors to \`frameColors\` array
4. Add new durations to \`frameDurations\` array

---
Generated by Sign-Sculptor Animation Sequence System
Assembly Time: ~2.5 hours
Skill Level: Intermediate
`;
}

/**
 * Generate BOM for animation sequence
 */
export function generateAnimationBOM(settings: AnimationSequenceSettings): string {
  const ledCost = (settings.ledCount / 60) * 12; // $12 per meter (60 LEDs)
  const controllerCost = settings.controllerType === 'esp32' ? 8 : 3;
  const powerSupplyCost = Math.ceil(settings.ledCount * 0.06 * 1.5) > 2 ? 8 : 5;
  const totalCost = ledCost + controllerCost + powerSupplyCost + 3;
  
  return `# Bill of Materials - ${settings.sequenceName}

## 3D Printed Parts:
${settings.frames.map((frame, i) => `${i + 1}. **Frame ${frame.frameNumber}** - ${frame.frameName}.stl - $${(1.5).toFixed(2)} (PLA)`).join('\n')}
${settings.frames.length + 1}. **Controller Housing** - $0.80 (PLA)

**Total 3D Printing Cost**: $${(settings.frameCount * 1.5 + 0.8).toFixed(2)}

## Electronic Components:

| Component | Quantity | Unit Cost | Total | Source |
|-----------|----------|-----------|-------|--------|
| ${settings.ledType.toUpperCase()} LED Strip (60 LEDs/m) | ${Math.ceil(settings.ledCount / 60)}m | $12.00 | $${ledCost.toFixed(2)} | Amazon/AliExpress |
| ${settings.controllerType.replace('_', ' ').toUpperCase()} | 1× | $${controllerCost.toFixed(2)} | $${controllerCost.toFixed(2)} | Amazon |
| 220Ω Resistor (1/4W) | 1× | $0.10 | $0.10 | Amazon |
| 5V Power Supply (${Math.ceil(settings.ledCount * 0.06 * 1.5)}A) | 1× | $${powerSupplyCost.toFixed(2)} | $${powerSupplyCost.toFixed(2)} | Amazon |
${settings.includeDimmer ? `| 50kΩ Potentiometer | 1× | $1.00 | $1.00 | Amazon |` : ''}
| 22 AWG Wire (red/black/yellow) | 2m | $1.00 | $1.00 | Amazon |
| JST Connectors (optional) | 3× | $0.30 | $0.90 | Amazon |
| Hot Glue Sticks | 3× | $0.10 | $0.30 | Local |

**Total Electronics Cost**: $${totalCost.toFixed(2)}

## Grand Total: $${(settings.frameCount * 1.5 + 0.8 + totalCost).toFixed(2)}

## Power Consumption:
- **LEDs**: ${settings.ledCount} × 60mA = ${(settings.ledCount * 0.06).toFixed(1)}A max
- **Controller**: ~50mA
- **Total**: ~${(settings.ledCount * 0.06 + 0.05).toFixed(1)}A
- **Recommended PSU**: ${Math.ceil(settings.ledCount * 0.06 * 1.5)}A (with safety margin)

## Print Settings:
- **Material**: White PLA or PETG
- **Layer Height**: 0.2mm
- **Infill**: 15%
- **Supports**: None
- **Print Time**: ${settings.frameCount * 2.5} hours total
- **Material Used**: ~${settings.frameCount * 35}g

## Where to Buy:
- **LED Strips**: Amazon (search "WS2812B LED strip 60 LEDs/meter")
- **Microcontroller**: Amazon, AliExpress
- **Power Supply**: Amazon (search "5V ${Math.ceil(settings.ledCount * 0.06 * 1.5)}A power adapter")
- **Components**: Amazon, Adafruit, SparkFun
- **3D Printing Filament**: Amazon, MatterHackers, Printed Solid

---
Generated by Sign-Sculptor Animation Sequence System
`;
}

/**
 * Generate frame geometry for 3D printing
 */
export function generateFrameGeometry(
  settings: AnimationSequenceSettings,
  frame: FrameConfig
): THREE.Group {
  const frameGroup = new THREE.Group();
  frameGroup.name = `Frame_${frame.frameNumber}_${frame.frameName}`;
  
  // Base panel
  const panelGeometry = new THREE.BoxGeometry(
    settings.signWidth,
    settings.signHeight,
    2 // 2mm thick panel
  );
  
  const panelMesh = new THREE.Mesh(
    panelGeometry,
    new THREE.MeshStandardMaterial({ color: 0xFFFFFF })
  );
  frameGroup.add(panelMesh);
  
  // LED mounting channels based on pattern
  frame.ledPattern.forEach((ledIndex) => {
    const ledPosition = calculateLEDPosition(ledIndex, settings);
    const ledChannel = createLEDChannel();
    ledChannel.position.set(ledPosition.x, ledPosition.y, 1);
    frameGroup.add(ledChannel);
  });
  
  return frameGroup;
}

/**
 * Calculate LED position on panel
 */
function calculateLEDPosition(ledIndex: number, settings: AnimationSequenceSettings): Point2D {
  // Simple grid layout for now
  const ledsPerRow = Math.ceil(Math.sqrt(settings.ledCount));
  const row = Math.floor(ledIndex / ledsPerRow);
  const col = ledIndex % ledsPerRow;
  
  const spacingX = settings.signWidth / (ledsPerRow + 1);
  const spacingY = settings.signHeight / (ledsPerRow + 1);
  
  return {
    x: (col + 1) * spacingX - settings.signWidth / 2,
    y: (row + 1) * spacingY - settings.signHeight / 2,
  };
}

/**
 * Create LED mounting channel
 */
function createLEDChannel(): THREE.Mesh {
  const channelGeometry = new THREE.BoxGeometry(12, 3, 2);
  const channelMesh = new THREE.Mesh(
    channelGeometry,
    new THREE.MeshStandardMaterial({ color: 0x303030 })
  );
  return channelMesh;
}
