import archiver from 'archiver';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import os from 'os';

const execAsync = promisify(exec);

interface EmojiMessageSettings {
  emojis: string[];
  layout: 'grid' | 'linear';
  gridColumns?: number;
  spacing: number;
  emojiSize: number;
  ledType: string;
  signHeight: number;
  wallThickness: number;
  baseThickness: number;
  wireHoleSpacing: number;
  includeBorder: boolean;
  borderWidth: number;
  borderPadding: number;
}

export async function generateEmojiMessage(settings: EmojiMessageSettings): Promise<Buffer> {
  const archive = archiver('zip', { zlib: { level: 9 } });
  const chunks: Buffer[] = [];

  archive.on('data', (chunk: Buffer) => chunks.push(chunk));

  const zipPromise = new Promise<Buffer>((resolve, reject) => {
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
  });

  // Create temporary directory for SCAD files
  const tempDir = path.join(os.tmpdir(), `emoji-message-${Date.now()}`);
  fs.mkdirSync(tempDir, { recursive: true });

  try {
    // Map LED type to channel width
    const ledChannelWidth = parseFloat(settings.ledType.replace('mm', ''));

    // Generate each emoji sign
    for (let i = 0; i < settings.emojis.length; i++) {
      const emoji = settings.emojis[i];
      const emojiName = getEmojiName(emoji, i);

      // Generate SCAD file for emoji body
      const scadContent = generateEmojiSCAD(emoji, emojiName, settings);
      const scadPath = path.join(tempDir, `Emoji_${emojiName}.scad`);
      fs.writeFileSync(scadPath, scadContent, 'utf-8');

      // Convert SCAD to STL for body
      const bodySTLPath = path.join(tempDir, `Emoji_${emojiName}_Body.stl`);
      await execAsync(`openscad -o "${bodySTLPath}" -D Render_Mode="Body" "${scadPath}"`);
      if (fs.existsSync(bodySTLPath)) {
        archive.append(fs.createReadStream(bodySTLPath), { name: `Emoji_${emojiName}_Body.stl` });
      }

      // Convert SCAD to STL for lid
      const lidSTLPath = path.join(tempDir, `Emoji_${emojiName}_Lid.stl`);
      await execAsync(`openscad -o "${lidSTLPath}" -D Render_Mode="Lid" "${scadPath}"`);
      if (fs.existsSync(lidSTLPath)) {
        archive.append(fs.createReadStream(lidSTLPath), { name: `Emoji_${emojiName}_Lid.stl` });
      }

      // Include SCAD source file
      archive.append(scadContent, { name: `Emoji_${emojiName}.scad` });
    }

    // Generate border frame if enabled
    if (settings.includeBorder) {
      const borderSCAD = generateBorderSCAD(settings);
      const borderPath = path.join(tempDir, 'Border_Frame.scad');
      fs.writeFileSync(borderPath, borderSCAD, 'utf-8');

      const borderSTLPath = path.join(tempDir, 'Border_Frame.stl');
      await execAsync(`openscad -o "${borderSTLPath}" "${borderPath}"`);
      if (fs.existsSync(borderSTLPath)) {
        archive.append(fs.createReadStream(borderSTLPath), { name: 'Border_Frame.stl' });
      }
      archive.append(borderSCAD, { name: 'Border_Frame.scad' });
    }

    // Generate assembly instructions
    const instructions = generateAssemblyInstructions(settings);
    archive.append(instructions, { name: 'ASSEMBLY_INSTRUCTIONS.md' });

    // Generate BOM
    const bom = generateBOM(settings);
    archive.append(bom, { name: 'BOM.md' });

    archive.finalize();
    return zipPromise;
  } finally {
    // Cleanup temp directory
    if (fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }
}

function getEmojiName(emoji: string, index: number): string {
  const emojiNames: Record<string, string> = {
    '😂': 'LOL',
    '❤️': 'Heart',
    '🔥': 'Fire',
    '😭': 'Crying',
    '🙏': 'PrayingHands',
    '😍': 'HeartEyes',
    '👍': 'ThumbsUp',
    '💯': 'Hundred',
    '🤔': 'Thinking',
    '💀': 'Skull',
    '😊': 'Smile',
    '😁': 'Grin',
    '😎': 'Cool',
    '😉': 'Wink',
    '😘': 'Kiss',
    '😱': 'Shocked',
    '😠': 'Angry',
    '😢': 'Sad',
    '😴': 'Sleepy',
    '🥳': 'Party',
    '🚀': 'Rocket',
    '⭐': 'Star',
    '⚡': 'Lightning',
    '🎉': 'Confetti',
    '💯': 'Hundred',
  };
  return emojiNames[emoji] || `Emoji_${index + 1}`;
}

function generateEmojiSCAD(emoji: string, emojiName: string, settings: EmojiMessageSettings): string {
  const ledChannelWidth = parseFloat(settings.ledType.replace('mm', ''));
  const lightType = `Silicone_Neon_${settings.ledType}`;
  
  return `// AUTOMATICALLY GENERATED FILE: Emoji_${emojiName}
// EMOJI: ${emoji}
// Generated by Sign-Sculptor Emoji Message Designer

Render_Mode = "Body";  // Change to "Lid" for diffuser
Emoji = "${emoji}";
Emoji_Size = ${settings.emojiSize};
Font_Name = "Segoe UI Emoji";  // Windows system emoji font
Light_Type = "${lightType}";

// -- Engineering Constants --
Sign_Height = ${settings.signHeight};
Wall_Thickness = ${settings.wallThickness};
Base_Thickness = ${settings.baseThickness};
Lid_Tolerance = 0.15;
Hole_Height = 5.0;
Hole_Size = 5.0;
Wire_Hole_Spacing = ${settings.wireHoleSpacing};

// -- Logic Engine --
CW = ${ledChannelWidth};
Lip_Overhang = ${ledChannelWidth <= 8 ? '0.4' : '0.0'};

$fn = 60;

module emoji_shape() {
    text(text=Emoji, size=Emoji_Size, font=Font_Name, halign="center", valign="center");
}

module body_geometry() {
    difference() {
        // Positive Block
        linear_extrude(Sign_Height)
            offset(r = CW/2 + Wall_Thickness)
            emoji_shape();

        // Light Channel
        translate([0,0, Base_Thickness])
            linear_extrude(Sign_Height + 1)
            offset(r = CW/2)
            emoji_shape();

        // Friction Lip
        if (Lip_Overhang > 0) {
            translate([0,0, Sign_Height - 2.0])
                linear_extrude(3.0)
                difference() {
                    offset(r = CW/2 + 5) emoji_shape();
                    offset(r = CW/2 - Lip_Overhang) emoji_shape();
                }
        }
        
        // Lid Shelf
        translate([0,0, Sign_Height - 2.0])
            linear_extrude(3.0)
            offset(r = CW/2 + 1.5)
            emoji_shape();

        // Side Holes for LED wiring
        translate([-Emoji_Size/1.8, 0, Hole_Height + Base_Thickness])
            rotate([0, 90, 0]) cylinder(h = Emoji_Size, r = Hole_Size/2);
            
        translate([Emoji_Size/1.8, 0, Hole_Height + Base_Thickness])
            rotate([0, -90, 0]) cylinder(h = Emoji_Size, r = Hole_Size/2);
    }
}

module lid_geometry() {
    color("White")
        linear_extrude(2.0)
        offset(r = (CW/2 + 1.5) - Lid_Tolerance)
        emoji_shape();
}

if (Render_Mode == "Body") { body_geometry(); }
else if (Render_Mode == "Lid") { lid_geometry(); }
`;
}

function generateBorderSCAD(settings: EmojiMessageSettings): string {
  const totalWidth = settings.layout === 'grid' 
    ? (settings.gridColumns || 3) * settings.emojiSize + ((settings.gridColumns || 3) - 1) * settings.spacing
    : settings.emojis.length * settings.emojiSize + (settings.emojis.length - 1) * settings.spacing;
  
  const rows = settings.layout === 'grid' 
    ? Math.ceil(settings.emojis.length / (settings.gridColumns || 3))
    : 1;
  const totalHeight = rows * settings.emojiSize + (rows - 1) * settings.spacing;
  
  const frameWidth = totalWidth + settings.borderPadding * 2;
  const frameHeight = totalHeight + settings.borderPadding * 2;
  
  return `// Border Frame for Emoji Message
// Generated by Sign-Sculptor

Frame_Width = ${frameWidth};
Frame_Height = ${frameHeight};
Border_Width = ${settings.borderWidth};
Frame_Thickness = 3;

$fn = 60;

difference() {
    // Outer frame
    linear_extrude(Frame_Thickness)
        square([Frame_Width, Frame_Height], center=true);
    
    // Inner cutout
    translate([0, 0, -1])
        linear_extrude(Frame_Thickness + 2)
        square([Frame_Width - Border_Width * 2, Frame_Height - Border_Width * 2], center=true);
}
`;
}

function generateBOM(settings: EmojiMessageSettings): string {
  const emojiList = settings.emojis.join(' ');
  
  return `# Bill of Materials (BOM)
## Emoji Message Sign: ${emojiList}

Generated by Sign-Sculptor Emoji Message Designer

### 3D Printed Parts
${settings.emojis.map((emoji, i) => `- Emoji_${getEmojiName(emoji, i)}_Body.stl (1x) - Main shell with LED channel`).join('\n')}
${settings.emojis.map((emoji, i) => `- Emoji_${getEmojiName(emoji, i)}_Lid.stl (1x) - Diffuser cover`).join('\n')}
${settings.includeBorder ? '- Border_Frame.stl (1x) - Decorative frame\n' : ''}

### Electronics
- ${settings.ledType} Silicone Neon LED Strip: ${settings.emojis.length * settings.emojiSize}mm total length
- 22 AWG hookup wire: ~${settings.emojis.length * 200}mm
- Power supply: 5V USB or 4×AA battery holder (6V)
- Optional: On/off switch
- Optional: Brightness dimmer (PWM controller)

### Hardware
- Hot glue gun + glue sticks
- Soldering iron + solder
- Wire strippers
- Flush cutters

### Assembly Time
Estimated: ${settings.emojis.length * 15} minutes

### Print Settings
- Material: PLA or PETG
- Layer Height: 0.2mm
- Infill: 15-20% (bodies), 100% (lids for diffusion)
- Supports: None required
- Print Time: ~${settings.emojis.length * 2} hours total

---
Generated: ${new Date().toISOString()}
`;
}



function generateAssemblyInstructions(settings: EmojiMessageSettings): string {
  const emojiList = settings.emojis.join(' ');
  
  return `# Emoji Message Sign Assembly Instructions

## Your Message: ${emojiList}

Generated by Sign-Sculptor Emoji Message Designer

## Parts Included

### Emoji Signs
${settings.emojis.map((emoji, i) => `- ${emoji} Emoji_${getEmojiName(emoji, i)}_Body.stl (LED channel shell)`).join('\n')}
${settings.emojis.map((emoji, i) => `- ${emoji} Emoji_${getEmojiName(emoji, i)}_Lid.stl (flat diffuser)`).join('\n')}

${settings.includeBorder ? '### Border Frame\n- Border_Frame.stl (decorative frame)\n' : ''}

## Assembly Steps

### 1. Print All Parts
- **Emoji Bodies**: Print with 2-3 perimeters, 15-20% infill
- **Emoji Lids**: Print with 100% infill for light diffusion (or use white PETG)
${settings.includeBorder ? '- **Border Frame**: Print with 2-3 perimeters, 15% infill\n' : ''}

**Recommended Settings:**
- Layer Height: 0.2mm
- Nozzle Temp: 210°C (PLA) or 230°C (PETG)
- Bed Temp: 60°C (PLA) or 80°C (PETG)
- Print Speed: 50mm/s
- Supports: Only for domed lids

### 2. LED Strip Installation

**Materials Needed:**
- ${settings.ledType} silicone neon LED strip
- Wire (22 AWG recommended)
- Solder and soldering iron
- Hot glue or LED mounting tape

**Steps:**
1. Measure LED strip length for each emoji (approximately ${settings.emojiSize}mm per emoji)
2. Cut LED strips to size
3. Thread LED strip into LED channel of each emoji body
4. Secure with hot glue or mounting tape
5. Solder wires to LED strip connections

### 3. Wiring

**LED Connection:**
${settings.emojis.length > 1 ? `- Connect emojis in series: ${settings.emojis.map((e, i) => `${e}${i + 1}`).join(' → ')}` : '- Single emoji - connect directly to power'}
- Route wires through side holes in emoji bodies
- Connect to 5V USB power or 4×AA battery holder (6V)

**Wiring Diagram:**
\`\`\`
[Power] → [Emoji 1] → [Emoji 2] → ... → [Emoji ${settings.emojis.length}]
\`\`\`

### 4. Assembly

1. **Snap on Diffuser Lids:**
   - Align lid with emoji body
   - Press firmly until snap-fit engages
   - Check for even light diffusion

2. **Arrange Emojis:**
   - Position emojis with ${settings.spacing}mm spacing
   - ${settings.layout === 'grid' ? `Arrange in ${settings.gridColumns || 3} column grid` : 'Arrange in linear row'}
   - Use hot glue or double-sided tape to secure

3. **Attach Border Frame (if included):**
   - Align frame around emoji arrangement
   - Secure with glue or screws
   - Ensure frame doesn't block light

### 5. Mounting

**Wall Mount:**
- Use command strips for damage-free hanging
- Or use M3/M4 screws with wall anchors
- Ensure emojis are level

## LED Specifications

- **Channel Width:** ${settings.ledType}
- **Voltage:** 5V (USB) or 6V (4×AA batteries)
- **Current:** Depends on LED strip length (typically 20-60mA per emoji)
- **Color:** Customizable (order appropriate LED color)

## Troubleshooting

**LEDs not lighting:**
- Check battery polarity
- Verify solder connections
- Test battery voltage
- Check for wire breaks

**Uneven lighting:**
- Adjust LED strip position in channel
- Ensure diffuser lid is seated properly
- Check for gaps in LED strip

**Lid won't snap:**
- Check for print warping
- Sand edges if too tight
- Verify tolerance settings

## Customization

- **LED Colors:** Use RGB strips for color changing
- **Brightness:** Add dimmer switch or PWM controller
- **Animation:** Use addressable LEDs (WS2812B) with Arduino
- **Power:** Add on/off switch to battery holder

## Safety

⚠️ **Important:**
- Use appropriate voltage for LED strips
- Don't exceed LED current ratings
- Ensure proper insulation of connections
- Keep batteries away from metal objects
- Supervise children with battery-powered signs

---

**Enjoy your custom emoji message LED sign!**

For support or questions, visit: https://sign-sculptor.com

Generated: ${new Date().toISOString()}
Settings: ${settings.emojiSize}mm emojis, ${settings.spacing}mm spacing, ${settings.ledType} LEDs
`;
}
