/**
 * FastLED Arduino Code Generator
 * Generates complete .ino files for WS2812B LED control
 * Based on Modular RGB LED Sign reference project
 * Includes 8 animation modes + encoder control
 */

interface FastLEDCodeSettings {
  // LED configuration
  numLEDs: number;
  ledPin: number;
  ledType: 'WS2812B' | 'WS2811' | 'WS2812';
  colorOrder: 'GRB' | 'RGB' | 'BRG';
  
  // Character mapping (for per-character color control)
  characterMap: number[]; // First LED index for each character
  numCharacters: number;
  
  // Encoder configuration
  includeEncoder: boolean;
  encoderClkPin: number;
  encoderDtPin: number;
  encoderSwPin: number;
  
  // Animation settings
  brightness: number; // 0-255
  framesPerSecond: number;
  
  // Default colors for freeColor mode
  defaultColors: string[]; // Color names per character
  
  // Project metadata
  projectName: string;
  author: string;
  description: string;
}

const defaultFastLEDSettings: FastLEDCodeSettings = {
  numLEDs: 14,
  ledPin: 3,
  ledType: 'WS2812B',
  colorOrder: 'GRB',
  
  characterMap: [0, 2, 4, 6, 8, 10, 12, 14], // 7 characters, 2 LEDs each
  numCharacters: 7,
  
  includeEncoder: true,
  encoderClkPin: 8,
  encoderDtPin: 9,
  encoderSwPin: 10,
  
  brightness: 255,
  framesPerSecond: 60,
  
  defaultColors: ['White', 'Red', 'Lime', 'Blue', 'Yellow', 'Plum', 'Gold'],
  
  projectName: 'Neon_Sign',
  author: 'Sign-Sculptor',
  description: 'WS2812B addressable LED neon sign with encoder control',
};

/**
 * Generate complete FastLED Arduino code
 */
export function generateFastLEDCode(
  settings: FastLEDCodeSettings = defaultFastLEDSettings
): string {
  const characterMapStr = settings.characterMap.join(',');
  const colorSetStr = settings.defaultColors.map((_, i) => i + 1).join(',');
  
  return `// ${settings.projectName}.ino
// Description: 
//    ${settings.description}
//    Based on FastLED library with encoder control for brightness and color selection.
//    
//    Encoder functions:
//    - Short press: Toggles sign ON/OFF
//    - Long press: Increments animation modes
//    - Turning: Adjusts brightness (or selects color in freeColor mode)
//
// Usage:
//    Developed for Seeed Studio XIAO SAMD21, compatible with Arduino UNO boards.
//    Install FastLED and Encoder libraries before uploading.
//
// Author: 
//    ${settings.author}
//
// Generated by Sign-Sculptor - https://github.com/yourusername/sign-sculptor

#include <FastLED.h>
${settings.includeEncoder ? '#include <Encoder.h>' : ''}

FASTLED_USING_NAMESPACE

#if defined(FASTLED_VERSION) && (FASTLED_VERSION < 3001000)
#warning "Requires FastLED 3.1 or later; check github for latest code."
#endif

// LED Configuration
#define LED_PIN     ${settings.ledPin}
#define LED_TYPE    ${settings.ledType}
#define COLOR_ORDER ${settings.colorOrder}
#define NUM_LEDS    ${settings.numLEDs}
CRGB leds[NUM_LEDS];

#define BRIGHTNESS          ${settings.brightness}
#define FRAMES_PER_SECOND   ${settings.framesPerSecond}
${settings.includeEncoder ? `#define ENC_SWITCH  ${settings.encoderSwPin}` : ''}

// Character-to-LED mapping
// Each element is the first LED index for that character
int FirstLedInChar[] = {${characterMapStr}};

// Color palette (13 colors)
CRGB color[] = {
  CRGB::White, CRGB::Red, CRGB::Lime, CRGB::Blue, 
  CRGB::DodgerBlue, CRGB::Yellow, CRGB::Plum, 
  CRGB::LightSalmon, CRGB::Fuchsia, CRGB::Gold, 
  CRGB::Magenta, CRGB::Brown, CRGB::OrangeRed
};

// Default startup colors for each character (freeColor mode)
int colorSet[] = {${colorSetStr}};

unsigned long timer = 0;

${settings.includeEncoder ? `
// Encoder setup
Encoder Enc(${settings.encoderClkPin}, ${settings.encoderDtPin});
long newPosition = 0;
long oldPosition = 0;
volatile byte SW_state = 0;
` : ''}

int mode = 1; // Current animation mode
bool onOff = true; // Sign ON/OFF state
uint8_t brightness = 10; // Current brightness level

void setup() {
  delay(3000); // 3 second delay for recovery
  ${settings.includeEncoder ? `pinMode(ENC_SWITCH, INPUT_PULLUP);` : ''}
  
  // Initialize FastLED
  FastLED.addLeds<${settings.ledType}, LED_PIN, ${settings.colorOrder}>(leds, NUM_LEDS);
  FastLED.setBrightness(BRIGHTNESS);
  
  ${settings.includeEncoder ? `attachInterrupt(digitalPinToInterrupt(ENC_SWITCH), EncSW, FALLING);` : ''}
  
  // Startup animation
  for(int i = 0; i < 3; i++) {
    fill_solid(leds, NUM_LEDS, CRGB::Purple);
    FastLED.show();
    delay(200);
    fill_solid(leds, NUM_LEDS, CRGB::Black);
    FastLED.show();
    delay(200);
  }
}

// List of animation patterns
typedef void (*SimplePatternList[])();
SimplePatternList gPatterns = { rainbow, rainbowWithGlitter, confetti, sinelon, juggle, bpm };

uint8_t gCurrentPatternNumber = 0; // Current pattern index
uint8_t gHue = 0; // Rotating base color

${settings.includeEncoder ? `
// Encoder interrupt handler
void EncSW() {
  SW_state++;
}
` : ''}

void loop() {
  // Mode selection
  if(mode == 1) {
    // Auto-cycle mode: change patterns every 10 seconds
    EVERY_N_SECONDS(10) { nextPattern(); }
  }
  else if((mode > 1) && (mode < 7)) {
    // Fixed pattern mode
    gCurrentPatternNumber = mode - 2;
  }
  else if(mode == 7) {
    // FreeColor mode: set colors per character
    drawFreeColors();
    setFreeColors();
  }
  else if(mode == 8) {
    // FreeColor display mode
    drawFreeColors();
  }

  // Execute current pattern
  if(mode < 7) {
    gPatterns[gCurrentPatternNumber]();
  }

  // Update display
  FastLED.show();
  FastLED.delay(1000 / FRAMES_PER_SECOND);

  // Slowly cycle base color
  EVERY_N_MILLISECONDS(20) { gHue++; }

  ${settings.includeEncoder ? `
  // Check encoder
  newPosition = Enc.read();
  updateBrightness();
  checkSwitch();
  ` : ''}
}

#define ARRAY_SIZE(A) (sizeof(A) / sizeof((A)[0]))

// ============================================
// ANIMATION FUNCTIONS
// ============================================

void rainbow() {
  // FastLED's built-in rainbow generator
  fill_rainbow(leds, NUM_LEDS, gHue, 7);
}

void rainbowWithGlitter() {
  // Rainbow plus random sparkly glitter
  rainbow();
  addGlitter(80);
}

void addGlitter(fract8 chanceOfGlitter) {
  if(random8() < chanceOfGlitter) {
    leds[random16(NUM_LEDS)] += CRGB::White;
  }
}

void confetti() {
  // Random colored speckles that blink in and fade smoothly
  fadeToBlackBy(leds, NUM_LEDS, 10);
  int pos = random16(NUM_LEDS);
  leds[pos] += CHSV(gHue + random8(64), 200, 255);
}

void sinelon() {
  // A colored dot sweeping back and forth, with fading trails
  fadeToBlackBy(leds, NUM_LEDS, 20);
  int pos = beatsin16(13, 0, NUM_LEDS - 1);
  leds[pos] += CHSV(gHue, 255, 192);
}

void bpm() {
  // Colored stripes pulsing at a defined Beats-Per-Minute
  uint8_t BeatsPerMinute = 62;
  CRGBPalette16 palette = PartyColors_p;
  uint8_t beat = beatsin8(BeatsPerMinute, 64, 255);
  for(int i = 0; i < NUM_LEDS; i++) {
    leds[i] = ColorFromPalette(palette, gHue + (i * 2), beat - gHue + (i * 10));
  }
}

void juggle() {
  // Eight colored dots, weaving in and out of sync
  fadeToBlackBy(leds, NUM_LEDS, 20);
  byte dothue = 0;
  for(int i = 0; i < 8; i++) {
    leds[beatsin16(i + 7, 0, NUM_LEDS - 1)] |= CHSV(dothue, 200, 255);
    dothue += 32;
  }
}

// ============================================
// FREE COLOR MODE (Per-Character Colors)
// ============================================

void drawFreeColors() {
  // Draw current color set for each character
  int k = 1;
  for(int s = 0; s < NUM_LEDS; s++) {
    if(s < FirstLedInChar[k]) {
      leds[s] = color[colorSet[k - 1]];
    }
    else {
      k++;
      leds[s] = color[colorSet[k - 1]];
    }
  }
  FastLED.show();
}

void setFreeColors() {
  // Interactive color selection for each character
  int toutCount = 0;
  int k = 1;
  timer = millis();
  
  while((k < ARRAY_SIZE(FirstLedInChar)) && (toutCount < 10)) {
    toutCount = 0;
    
    while((SW_state == 0) && (toutCount < 10)) {
      // Blink current character
      if((millis() - timer) < 800) {
        for(int s = FirstLedInChar[k - 1]; s < FirstLedInChar[k]; s++) {
          leds[s] = color[colorSet[k - 1]];
        }
      }
      else if((millis() - timer) < 1000) {
        for(int s = FirstLedInChar[k - 1]; s < FirstLedInChar[k]; s++) {
          leds[s] = CRGB::Black;
        }
      }
      else {
        timer = millis();
        toutCount++;
      }
      
      FastLED.show();
      
      ${settings.includeEncoder ? `
      // Check encoder for color change
      newPosition = Enc.read();
      delay(200);
      newPosition = Enc.read(); // Discard double increment
      
      if(newPosition < oldPosition) {
        if(colorSet[k - 1] > 0) {
          colorSet[k - 1] = colorSet[k - 1] - 1;
        }
        timer = millis();
      }
      else if(newPosition > oldPosition) {
        if(colorSet[k - 1] < (ARRAY_SIZE(color) - 1)) {
          colorSet[k - 1] = colorSet[k - 1] + 1;
        }
        timer = millis();
      }
      
      oldPosition = newPosition;
      ` : ''}
    }
    
    // Re-write color if clicked when black
    for(int s = FirstLedInChar[k - 1]; s < FirstLedInChar[k]; s++) {
      leds[s] = color[colorSet[k - 1]];
    }
    
    k++;
    delay(200); // Avoid double jump
    SW_state = 0;
  }
  
  mode = 8; // Switch to freeColor display mode
}

// ============================================
// ENCODER CONTROL FUNCTIONS
// ============================================

${settings.includeEncoder ? `
void checkSwitch() {
  if(SW_state > 0) {
    delay(500);
    
    if(!digitalRead(ENC_SWITCH)) {
      // Long press: Change mode
      if(mode > 7) {
        mode = 1;
      }
      else {
        mode++;
      }

      // Visual feedback: blink red
      FastLED.clear(true);
      for(int s = 0; s < mode; s++) {
        fill_solid(leds, NUM_LEDS, CRGB::Red);
        FastLED.show();
        delay(200);
        fill_solid(leds, NUM_LEDS, CRGB::Black);
        FastLED.show();
        delay(200);
      }
      SW_state = 0;
    }
    else {
      // Short click: Toggle ON/OFF
      if(onOff) {
        // Turn OFF with fade
        for(int i = 0; i < 100; i++) {
          fadeToBlackBy(leds, NUM_LEDS, 10);
          FastLED.show();
          delay(10);
        }
      }
      else {
        // Turn ON
        if(mode == 8) {
          mode = 7; // Re-enter freeColor mode
        }
      }
      
      onOff = !onOff;
      SW_state = 0;

      // Wait for button release
      while(!onOff && (SW_state == 0)) {}
    }
  }
}

void updateBrightness() {
  // Adjust brightness based on encoder rotation
  if((newPosition < oldPosition) && (brightness > 0)) {
    brightness--;
  }
  else if((newPosition > oldPosition) && (brightness < 50)) {
    brightness++;
  }

  // Exponential brightness curve for better control
  if(brightness >= 35) {
    FastLED.setBrightness(map(brightness, 35, 50, 10, 1));
  }
  else {
    FastLED.setBrightness(map(brightness, 0, 35, 255, 10));
  }

  oldPosition = newPosition;
}
` : `
// No encoder control - brightness is fixed
`}

void nextPattern() {
  // Cycle to next animation pattern
  gCurrentPatternNumber = (gCurrentPatternNumber + 1) % ARRAY_SIZE(gPatterns);
}

// ============================================
// END OF CODE
// ============================================
`;
}

/**
 * Generate character-to-LED mapping based on text/shape
 */
export function generateCharacterMap(
  text: string,
  ledsPerCharacter: number = 2
): { characterMap: number[]; numLEDs: number; numCharacters: number } {
  const numCharacters = text.length;
  const characterMap: number[] = [];
  
  for (let i = 0; i <= numCharacters; i++) {
    characterMap.push(i * ledsPerCharacter);
  }
  
  const numLEDs = numCharacters * ledsPerCharacter;
  
  return {
    characterMap,
    numLEDs,
    numCharacters,
  };
}

/**
 * Generate installation instructions for Arduino IDE
 */
export function generateArduinoInstallInstructions(
  controllerType: 'xiao_samd21' | 'arduino_nano' | 'esp32' = 'xiao_samd21'
): string {
  const boardName = controllerType === 'xiao_samd21' ? 'Seeeduino XIAO' :
                    controllerType === 'arduino_nano' ? 'Arduino Nano' :
                    'ESP32 Dev Module';
  
  const boardUrl = controllerType === 'xiao_samd21' ? 
    'https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json' :
    controllerType === 'esp32' ?
    'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json' :
    ''; // Arduino Nano is built-in
  
  return `
# Arduino IDE Setup Instructions

## 1. Install Arduino IDE
- Download from: https://www.arduino.cc/en/software
- Install version 2.0 or later (recommended)

## 2. Install Board Support
${controllerType === 'xiao_samd21' || controllerType === 'esp32' ? `
### Add Board Manager URL:
1. Open Arduino IDE
2. Go to **File → Preferences**
3. In "Additional Boards Manager URLs", add:
   \`\`\`
   ${boardUrl}
   \`\`\`
4. Click OK

### Install Board Package:
1. Go to **Tools → Board → Boards Manager**
2. Search for "${controllerType === 'xiao_samd21' ? 'Seeeduino' : 'ESP32'}"
3. Install "${controllerType === 'xiao_samd21' ? 'Seeed SAMD Boards' : 'ESP32 by Espressif Systems'}"
4. Wait for installation to complete
` : `
### Arduino Nano:
- Board support is built-in to Arduino IDE
- No additional installation needed
`}

## 3. Install Required Libraries

### FastLED Library:
1. Go to **Tools → Manage Libraries**
2. Search for "FastLED"
3. Install "FastLED by Daniel Garcia"
4. Version 3.5.0 or later

### Encoder Library:
1. In Library Manager, search for "Encoder"
2. Install "Encoder by Paul Stoffregen"
3. Version 1.4.2 or later

## 4. Select Board and Port

### Board Selection:
1. Go to **Tools → Board**
2. Select: **${boardName}**

### Port Selection:
1. Connect ${controllerType.toUpperCase().replace('_', ' ')} via USB
2. Go to **Tools → Port**
3. Select the COM port (Windows) or /dev/tty.usbmodem (Mac/Linux)
4. If no port appears, install USB drivers:
${controllerType === 'xiao_samd21' ? 
  '   - Windows: https://files.seeedstudio.com/wiki/Seeeduino-XIAO/res/Seeed_USB_Driver_v2.1.zip' :
  controllerType === 'esp32' ?
  '   - Usually auto-detected, or install CP210x drivers' :
  '   - Usually auto-detected, or install CH340 drivers'}

## 5. Upload Code

1. Open the generated .ino file in Arduino IDE
2. Verify code: Click **✓ Verify** button
3. Upload code: Click **→ Upload** button
4. Wait for "Done uploading" message
5. Open **Tools → Serial Monitor** to see debug output

## 6. Troubleshooting

### "Board not found" error:
- Check USB cable (must support data, not just power)
- Try different USB port
- Restart Arduino IDE
- Re-install board drivers

### "Library not found" error:
- Verify FastLED and Encoder libraries are installed
- Check library version compatibility
- Restart Arduino IDE

### Upload fails:
${controllerType === 'xiao_samd21' ?
  '- Double-tap RESET button to enter bootloader mode\n- Upload within 8 seconds' :
  controllerType === 'esp32' ?
  '- Hold BOOT button while uploading\n- Release after "Connecting..." appears' :
  '- Select correct processor (ATmega328P)\n- Try "Old Bootloader" option'}

### LEDs don't light up:
- Check wiring (especially 220Ω resistor on data line)
- Verify 5V power supply is adequate
- Check LED strip polarity (DI = Data In)
- Test with single LED first

## 7. Testing

After successful upload:
1. **Encoder rotation** → Brightness changes
2. **Short press** → Sign turns ON/OFF
3. **Long press** → Mode changes (red blinks indicate mode number)
4. **Mode 1** → Auto-cycle animations
5. **Mode 2-6** → Fixed animations
6. **Mode 7** → Per-character color selection

## 8. Serial Monitor Commands

Open Serial Monitor (115200 baud) to see:
- Current mode
- Brightness level
- Encoder position
- Button presses

Enjoy your RGB neon sign! 🌈✨
`;
}

export { FastLEDCodeSettings, defaultFastLEDSettings };
