import cv2
import numpy as np
import os

# ==========================================
#   THE SCOTT ENGINE: IMAGE TO MANIFESTATION
# ==========================================
# Purpose: Transform any PNG/JPG into a hollowed, channeled 3D model.

class ScottSignEngine:
    def __init__(self, tolerance=2.0, light_type="silicone_neon_6mm"):
        self.tolerance = tolerance
        self.light_type = light_type
        self.scad_template = """
// AUTOMATICALLY GENERATED BY SCOTT ENGINE
// Source: {source_name}
$fn = 60;

// --- Configuration ---
Render_Mode = "Body"; // Options: "Body", "Lid"
Sign_Height = 30;
Wall_Thickness = 2;
Base_Thickness = 2;
Lid_Tolerance = 0.15;

// -- Engineering Constants (Scott Algorithm Derived) --
CW = ({light_type} == "silicone_neon_6mm") ? 6.0 : 8.0; 
Lip_Overhang = 0.4;

module core_shape() {{
    // Scott-Peucker Optimized Vector Path
    polygon(points={points});
}}

module body_geometry() {{
    difference() {{
        linear_extrude(Sign_Height) offset(r = CW/2 + Wall_Thickness) core_shape();
        translate([0, 0, Base_Thickness]) linear_extrude(Sign_Height + 1) offset(r = CW/2) core_shape();
        
        // Friction Lip for Snap-Fit
        translate([0, 0, Sign_Height - 2.0]) linear_extrude(3.0)
            difference() {{
                offset(r = CW/2 + 5) core_shape();
                offset(r = CW/2 - Lip_Overhang) core_shape();
            }}
    }}
}}

module lid_geometry() {{
    linear_extrude(2.0) offset(r = (CW/2 + 1.5) - Lid_Tolerance) core_shape();
}}

if (Render_Mode == "Body") {{ body_geometry(); }}
else {{ lid_geometry(); }}
"""

    def process_image(self, image_path):
        # 1. Load and Binarize (Stage 1: Boundary Manifestation)
        img = cv2.imread(image_path, 0)
        _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
        
        # 2. Extract Contours (Moore-Neighbor Logic)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if not contours:
            return "No boundary detected."

        # 3. Scott-Peucker Simplification (Stage 2: Geodesic Distillation)
        # We take the largest contour and reduce points while preserving topological truth.
        main_contour = max(contours, key=cv2.contourArea)
        epsilon = self.tolerance * cv2.arcLength(main_contour, True) / 100.0
        approx_points = cv2.approxPolyDP(main_contour, epsilon, True)
        
        # Convert to list of [x, y] for OpenSCAD
        points_list = [[float(p[0][0]), float(-p[0][1])] for p in approx_points]

        # 4. Generate the SCAD File
        scad_output = self.scad_template.format(
            source_name=os.path.basename(image_path),
            light_type=f'"{self.light_type}"',
            points=points_list
        )
        
        output_name = image_path.split('.')[0] + ".scad"
        with open(output_name, "w") as f:
            f.write(scad_output)
            
        print(f"--- Manifestation Complete: {output_name} ---")

if __name__ == "__main__":
    engine = ScottSignEngine(tolerance=1.5)
    # Input any visible image (PNG/JPG)
    engine.process_image("your_image_here.png")